### PR TITLE
fix: update user_code_error schema to handle error objects

### LINKED ISSUE #1894: `bun run dev` fails due to user_code_error validation error
### Description
The development environment (`bun run dev`) fails when autoloading packages due to a Zod validation error. The error occurs when fetching package `seveibar/smd-usb-c` from the production API.

### Error Details (screenshot)

Image

```bash
[autoload-dev-pkgs] 📦 Loaded seveibar/usb-c-flashlight
[autoload-dev-pkgs] 📦 Fetching package seveibar/push-button...
[autoload-dev-pkgs] 📦 Loaded seveibar/push-button
[autoload-dev-pkgs] 📦 Fetching package seveibar/smd-usb-c...
file:///Users/ansh/tscircuit.com/node_modules/zod/v3/types.js:39
                const error = new ZodError(ctx.common.issues);
                              ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "object",
    "path": [
      "user_code_error"
    ],
    "message": "Expected string, received object"
  }
]
    at get error (file:///Users/ansh/tscircuit.com/node_modules/zod/v3/types.js:39:31)
    at ZodObject.parse (file:///Users/ansh/tscircuit.com/node_modules/zod/v3/types.js:114:22)
    at Object.addPackageRelease (file:///Users/ansh/tscircuit.com/node_modules/.vite-temp/vite.config.ts.timestamp-1761483505028-f419e368db0a7.mjs:4004:41)
    at Object.value (file:///Users/ansh/tscircuit.com/node_modules/zustand-hoist/lib/hoist-actions.js:8:49)
    at loadPackageWithDependencies (file:///Users/ansh/tscircuit.com/node_modules/.vite-temp/vite.config.ts.timestamp-1761483505028-f419e368db0a7.mjs:936:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async loadPackageWithDependencies (file:///Users/ansh/tscircuit.com/node_modules/.vite-temp/vite.config.ts.timestamp-1761483505028-f419e368db0a7.mjs:960:23)
    at async loadAutoloadPackages (file:///Users/ansh/tscircuit.com/node_modules/.vite-temp/vite.config.ts.timestamp-1761483505028-f419e368db0a7.mjs:990:21) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'object',
      path: [ 'user_code_error' ],
      message: 'Expected string, received object'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'object',
      path: [ 'user_code_error' ],
      message: 'Expected string, received object'
    }
  ]
}

Node.js v22.18.0
error: script "dev" exited with code 1
bash-3.2$ 
```

### Steps to Reproduce
1. Run `bun run dev`
2. Wait for package autoloading to begin
3. Error occurs when fetching `seveibar/smd-usb-c` package

### Expected Behavior
Development environment should start successfully and load all packages without validation errors.

### Actual Behavior
Development environment crashes with ZodError during package autoload.

### Environment
- Node.js v22.18.0
- Bun runtime
- macOS (darwin 24.6.0)

### Related
- Introduced in commit 6ca4185 (PR #1871) which added `user_code_error` field to schema

**Workaround:**
None currently available - development environment is completely blocked.

### PR DESCRIPTION
**Pull request by divanshu-go**
fixes #1894

### Problem
The development environment fails to start when autoloading packages due to a Zod validation error. The production API (`https://api.tscircuit.com`) returns `user_code_error` as an object, but the local schema expects a string, causing validation to fail during package autoload.

### Root Cause
- Commit 6ca4185 (PR #1871) added `user_code_error` field to the schema as `z.string().nullable()`
- The production API (`https://api.tscircuit.com`) returns `user_code_error` as an object with `error_code` and `message` fields
- When autoloading packages in development, the object is passed directly to `db.addPackageRelease()` 
- Zod validation fails because it receives an object but expects a string

### Solution
Updated the schema to use `errorSchema.nullable()` instead of `z.string().nullable()` for the `user_code_error` field. This makes it consistent with:
- How the production API returns error objects
- How other error fields are defined in the schema (`order.error`, `orderQuote.error`)
- The existing `errorSchema` pattern that expects objects with `error_code` and `message` fields

### Testing
- [x] `bun run dev` starts successfully
- [x] Packages load without validation errors

image

### CODE REVIEW

**Review by imrishabh18 — CHANGES_REQUESTED** [review]
I am not sure if this is the right fix, the `user_code_error`should always be an object iiuc. Maybe the schema needs to change

File: src/components/preview/ConnectedRepoOverview.tsx [hunk 1]
```diff
@@ -496,13 +496,13 @@ export const ConnectedRepoOverview = ({
...
-                      packageRelease.user_code_error,
+                      packageRelease.user_code_error?.message || null,
                       packageRelease.user_code_completed_at,
                       userCodeJobInProgress,
                     ) === "success"
                       ? "default"
                       : getStepStatus(
-                            packageRelease.user_code_error,
+                            packageRelease.user_code_error?.message || null,
                             packageRelease.user_code_completed_at,
```
Comment (divanshu-go) [inline src/components/preview/ConnectedRepoOverview.tsx]: `getStepStatus` only needs to check presence, the direct property access (`?.message || null`) is better than calling `getErrorMessage()`. The function call is overkill when we just need a truthy/falsy value.
