### PR TITLE
fix: jlcpcb part already imported

### LINKED ISSUE #1078: [C5248081] Failed to import from JLCPCB
I tried to import the part number C5248081 from JLCPCB, but it failed. Here's the error I got:
```
Failed to generate snippet from JLCPCB part: undefined
```

Could be an issue in `fetchEasyEDAComponent` or `convertRawEasyEdaToTs`

### PR DESCRIPTION
**Pull request by techmannih**
fix #1078 
/claim #1078

### CODE REVIEW

File: src/components/JLCPCBImportDialog.tsx [hunk 1]
```diff
@@ -76,16 +70,20 @@ export function JLCPCBImportDialog({
           jlcpcb_part_number: partNumber,
         })
         .catch((e) => e)
+
```
Comment (Anshgrover23) [inline src/components/JLCPCBImportDialog.tsx:73]: @techmannih remove new lines.

**Review by Anshgrover23 — CHANGES_REQUESTED** [review]

File: src/components/JLCPCBImportDialog.tsx (hunk 1 above)
Comment (Anshgrover23) [reply src/components/JLCPCBImportDialog.tsx:73]: just remove these lines and bun run format again to see whats happening.

File: src/components/JLCPCBImportDialog.tsx [hunk 2]
```diff
@@ -27,6 +27,9 @@ export function JLCPCBImportDialog({
   const [partNumber, setPartNumber] = useState("")
   const [isLoading, setIsLoading] = useState(false)
   const [error, setError] = useState<string | null>(null)
+  const [alreadyImportedSnippetId, setAlreadyImportedSnippetId] = useState<
```
Comment (imrishabh18) [inline src/components/JLCPCBImportDialog.tsx:30]:
```suggestion
  const [importedPackageId, setImportedPackageId] = useState<
```

File: src/components/JLCPCBImportDialog.tsx [hunk 3]
```diff
@@ -121,32 +119,53 @@ export function JLCPCBImportDialog({
...
               </Button>
             </div>
           )}
+
+          {alreadyImportedPackageId && (
+            <p className="mt-2 text-sm text-green-600">
+              This part number has already been imported to your profile.{" "}
+              <PrefetchPageLink
+                className="text-blue-500 hover:underline"
+                href={`/editor?package_id=${alreadyImportedPackageId}`}
```
Comment (seveibar) [inline src/components/JLCPCBImportDialog.tsx:158]: feels like it would make more sense to not link to the editor, but to link to the package page, `/author/packageName`

**Review by seveibar — APPROVED** [review]

**Review by Anshgrover23 — APPROVED** [review]

File: src/components/JLCPCBImportDialog.tsx [hunk 4]
```diff
@@ -45,29 +48,20 @@ export function JLCPCBImportDialog({
 
     setIsLoading(true)
     setError(null)
+    setAlreadyImportedPackageId(null)
+
     try {
-      // Check that module doesn't already exist
-      const existingSnippetRes = await axios.get(
+      const existingPackageRes = await axios.get(
         `/snippets/get?owner_name=${session?.github_username}&unscoped_name=${partNumber}`,
```
Comment (imrishabh18) [inline src/components/JLCPCBImportDialog.tsx:55]: You should convert this call to packages

File: src/components/JLCPCBImportDialog.tsx [hunk 5]
```diff
@@ -45,29 +48,20 @@ export function JLCPCBImportDialog({
...
-                href={`/editor?package_id=${existingSnippetRes.data.snippet.snippet_id}`}
-              >
-                View {partNumber}
-              </PrefetchPageLink>
-            </div>
-          ),
-        })
+      if (existingPackageRes.status !== 404) {
+        const snippetId = existingPackageRes.data.snippet.snippet_id
+        setAlreadyImportedPackageId(snippetId)
```
Comment (imrishabh18) [inline src/components/JLCPCBImportDialog.tsx:63]:
```suggestion
        setAlreadyImportedPackageId(packageId)
```

**Review by imrishabh18 — CHANGES_REQUESTED** [review]
We should use `/packages` call everywhere

**Comment by MustafaMulla29** [comment]
> @imrishabh18 may be need rerun bun test workflow, this is failed now

I think you don't have to worry about the test. Its flaky, may pass in the next commit

**Review by Anshgrover23 — CHANGES_REQUESTED** [review]
@techmannih can u make  a bun test before we merge this pr importing the component "C1386" and show us that this is working fine?

**Review by imrishabh18 — APPROVED** [review]
Create a follow up PR for replacing this

**Review by Anshgrover23 — APPROVED** [review]
