### PR TITLE
fix(tree-view): correct syntax error in selectedTreeVariants and sync selected item

### LINKED ISSUE #876: hidden files showing

### LINKED ISSUE #881: selected file not being highlighted on initial load

### PR DESCRIPTION
**Pull request by ArnavK-09**
fix #876 
fix #881

refactor(FileSidebar): improve tree data transformation logic and handle hidden files

- Fix syntax error in `selectedTreeVariants` by removing an extra single quote
- Add `useEffect` to sync `selectedItemId` with `initialSelectedItemId` in `TreeView`
- Refactor `transformFilesToTreeData` to handle paths starting with a slash and filter hidden files
- Convert nested object structure to array structure for tree data

### CODE REVIEW

File: src/components/FileSidebar.tsx [hunk 1]
```diff
@@ -24,35 +25,57 @@ const FileSidebar: React.FC<FileSidebarProps> = ({
   const transformFilesToTreeData = (
     files: Record<FileName, string>,
   ): TreeDataItem[] => {
-    const root: { [key: string]: TreeDataItem } = {}
+    type TreeNode = Omit<TreeDataItem, "children"> & {
+      children?: Record<string, TreeNode>
+    }
```
Comment (seveibar) [inline src/components/FileSidebar.tsx:30]: always best to define types at the highest scope

**Review by seveibar — APPROVED** [review]
