### PR TITLE
fix(CodeEditor): ensure consistent path handling in fsMap

### LINKED ISSUE #948: typings not being updated on package preview
Image

### PR DESCRIPTION
**Pull request by ArnavK-09**
The commit ensures that paths in the `fsMap` are consistently prefixed with a forward slash if they don't already start with one. This prevents potential issues with path resolution in the virtual file system. Additionally, a debug log statement was added to inspect the keys of the `fsMap` for troubleshooting purposes.

##### /claim #948

close #948

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
On the backend, we actually intentionally _don't_ use the forward slash prefix, we should keep this consistent everywhere

At first i thought the forward slash prefix was the best solution, but for project-relative paths it interops better with CLI etc. to just not use the forward slash prefix

File: src/components/package-port/CodeEditor.tsx [hunk 1]
```diff
@@ -185,7 +185,7 @@ export const CodeEditor = ({
       delegate: {
         started: () => {
           const manualEditsTypeDeclaration = `
-				  declare module "*.json" {
+				  declare module "manual-edits.json" {
```
Comment (seveibar) [inline src/components/package-port/CodeEditor.tsx:188]: this is a nice fix

**Review by seveibar — APPROVED** [review]
