### PR TITLE
Fix/typescript dependency caching

### LINKED ISSUE #1696: Prevent re-download of typescript dependencies on package save (and cache in localStorage)
See how when I save, a million dependencies get downloaded? It's not supposed to do that

https://github.com/user-attachments/assets/590ac431-3b61-4bdb-b806-2774d4b960e0

/bounty $75

### PR DESCRIPTION
**Pull request by Sahelisaha04**
Fixes #1696
/claim #1696

https://github.com/user-attachments/assets/d048071b-5bbc-40df-9e58-5571a5f3831c

adding video

### CODE REVIEW

File: src/lib/ts-lib-cache.ts [hunk 1]
```diff
@@ -18,7 +18,8 @@ export async function loadDefaultLibMap(): Promise<Map<string, string>> {
   const missing: string[] = []
 
   for (const lib of libs) {
-    const cached = await get(CACHE_PREFIX + lib)
+    const cacheKey = `ts-lib-${TS_LIB_VERSION}-${lib}`
+    const cached = await get(cacheKey)
```
Comment (imrishabh18) [inline src/lib/ts-lib-cache.ts:22]: The ttl check is missing for the typescript lib files, I think the TTL check should happen for this too!

**Comment by seveibar** [comment]
This is pretty good

**Review by imrishabh18 — APPROVED** [review]
