### PR TITLE
fix tscircuit.com/search

### LINKED ISSUE #901: tscircuit.com/search is broken
https://tscircuit.com/search

/bounty $20

Also, it should say "Search Packages" (the term "snippets" is mostly being deprecated)

### PR DESCRIPTION
**Pull request by Ayushjhawar8**
/claim #901
fix #901

### CODE REVIEW

**Comment by seveibar** [comment]
idk about this appearance, the query parameter "q" should be used in the url so searches can be linked to CC @MustafaMulla29

**Comment by Ayushjhawar8** [comment]
@seveibar about the appearance, does making it left align makes it better?
image

**Comment by seveibar** [comment]
@Ayushjhawar8 no, look at the github search etc. its not a dropdown, they used the page and allow scrolling etc

**Comment by Ayushjhawar8** [comment]
image

**Comment by Ayushjhawar8** [comment]
seve now can you check its deployed at https://tscircuit-nae2r0svr-tscircuit.vercel.app/search

**Comment by seveibar** [comment]
When there is no search results because theyre loading, display a small circular loader in the space where search components are appearing, make sure its centered with padding

**Comment by MustafaMulla29** [comment]
@Ayushjhawar8 Hey, are you working on this?

**Comment by Ayushjhawar8** [comment]
@MustafaMulla29 yes

**Comment by Ayushjhawar8** [comment]
https://github.com/user-attachments/assets/2c517a0a-6002-4e30-afcc-c09b037ac60c
@seveibar please check

**Review by MustafaMulla29 — CHANGES_REQUESTED** [review]
Maybe use the snippet card used in the trending and user-profile page and also use a better loader

**Comment by seveibar** [comment]
@Ayushjhawar8 loader needs more vertical padding. The footer should not be jumping around and visible to the user, you can use min height etc but make sure the loader is visible

there are issues with the display of the component. @MustafaMulla29 is probably right that you should use an existing one otherwise we’ll be working on these details for a bit (eg Created text wraps below)

image

**Comment by seveibar** [comment]
Yea the author displaying twice is sloppy, make sure to check your designs

**Review by MustafaMulla29 — CHANGES_REQUESTED** [review]
'q'(query) should be visible in the url

**Comment by Ayushjhawar8** [comment]
https://github.com/user-attachments/assets/d05fba5f-a0cc-40e3-807a-eaa7c23814da

i tried to address all the comments. Let me know if any more changes needed.

**Review by MustafaMulla29 — COMMENTED** [review]
Also the cards are too wider, you can take reference from the trending and user-profile pages. @seveibar what do you think?

**Comment by Ayushjhawar8** [comment]
seve i removed the loader and changed to skeleton used in trending page etc, also made the q search work better while sharing, also changed layout to 3 by 3

File: src/components/SearchComponent.tsx [hunk 1]
```diff
@@ -91,17 +93,17 @@ const SearchComponent: React.FC<SearchComponentProps> = ({
   const shouldOpenInEditor = location === "/editor" || location === "/ai"
 
   return (
-    <form onSubmit={handleSearch} className="relative">
+    <form onSubmit={handleSearch} className="relative w-full">
```
Comment (seveibar) [inline src/components/SearchComponent.tsx:96]: does this still need to be changed? Make sure to not change files that aren't related to the PR

Comment (Ayushjhawar8) [reply src/components/SearchComponent.tsx:96]: oh yes this was when i was testing initially, let me remove this

File: src/components/PageSearchComponent.tsx [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+    }
+  }, [searchQuery, location, setLocation])
+
+  useEffect(() => {
+    const params = new URLSearchParams(window.location.search)
+    const urlQuery = params.get("q")
+    if (urlQuery !== null && urlQuery !== searchQuery) {
+      setSearchQuery(urlQuery)
+    }
+  }, [location])
```
Comment (seveibar) [inline src/components/PageSearchComponent.tsx:57]: antipattern. You can just use `useState(params.get("q") ?? "")`

Remember, every useEffect triggers a render and makes the page slow

```suggestion
```

File: src/components/PageSearchComponent.tsx [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+
+  useEffect(() => {
+    const baseUrl = location.split("?")[0]
+    const newUrl = searchQuery
+      ? `${baseUrl}?q=${encodeURIComponent(searchQuery)}`
+      : baseUrl
+    if (newUrl !== location) {
+      setLocation(newUrl)
+    }
+  }, [searchQuery, location, setLocation])
```
Comment (seveibar) [inline src/components/PageSearchComponent.tsx:49]: hmm i don't like this approach, you're removing all other url parameters, why not use the URLSearchParams object to do a proper construction rather than direct string manipulation

Note: remove location and setLocation from the useEffect to avoid potential infinite loops. Keep useEffects simple

File: src/pages/search.tsx [hunk 4]
```diff
@@ -1,25 +1,57 @@
...
+                <Search className="w-6 h-6 text-blue-500" />
+                <h1 className="text-3xl font-bold text-gray-900">
+                  Search Packages
+                </h1>
+              </div>
+              <p className="text-lg text-gray-600 mb-4">
+                Find circuit packages for your next project. Browse through our
+                collection of community-created circuit designs, footprints, and
+                components.
+              </p>
```
Comment (seveibar) [inline src/pages/search.tsx:29]:
```suggestion
```

File: src/pages/search.tsx [hunk 5]
```diff
@@ -1,25 +1,57 @@
...
+              <div className="flex flex-wrap gap-3">
+                <Badge variant="secondary" className="px-3 py-1">
+                  <Filter className="w-3.5 h-3.5 mr-1" />
+                  <span>Search by Name</span>
+                </Badge>
```
Comment (seveibar) [inline src/pages/search.tsx:34]:
```suggestion
```

3rd time i've mentioned removing this button that doesn't do anything. It looks like a button and doesn't do anything

Comment (Ayushjhawar8) [reply src/pages/search.tsx:34]: its like the tag we have in trending page, i took inspiration from, well we can remove it if not want

File: src/components/PageSearchComponent.tsx (hunk 3 above)
Comment (Ayushjhawar8) [reply src/components/PageSearchComponent.tsx]: okay i used `URLSearchParams` to properly manage query parameters hope so.

File: src/components/PageSearchComponent.tsx [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+    const baseUrl = location.split("?")[0]
+    const queryString = params.toString()
+    const newUrl = queryString ? `${baseUrl}?${queryString}` : baseUrl
+
+    if (newUrl !== location) {
+      setLocation(newUrl)
+    }
+  }
+
+  const shouldOpenInEditor = location === "/editor" || location === "/ai"
```
Comment (seveibar) [inline src/components/PageSearchComponent.tsx:63]:
```suggestion
```

**Comment by Ayushjhawar8** [comment]
Seve please check: https://tscircuit-psthdvpw7-tscircuit.vercel.app/search

**Review by MustafaMulla29 — CHANGES_REQUESTED** [review]
Screenshot_2025-04-22-08-58-36-02_40deb401b9ffe8e1df2f1cc5ba480b12
'Search' text should be fitting in mobile screens, currently its wrapping below.
Also i think its better to remove the white background card of the full search and results showing part. Coz it aligns with the trending page. @seveibar what do you think?

**Comment by seveibar** [comment]
Makes sense to be 👍 @MustafaMulla29

**Comment by Ayushjhawar8** [comment]
The search title for each package are overlapping due to `snippetCard` design, and its occuring everywhere its used.

I removed the white bg for consistency

File: src/components/PageSearchComponent.tsx [hunk 7]
```diff
@@ -0,0 +1,156 @@
...
+    () => new URLSearchParams(window.location.search).get("q") ?? "",
+  )
+
+  const { data: searchResults, isLoading: isLoadingSearchResults } = useQuery(
+    ["snippetSearch", searchQuery],
+    async () => {
+      if (!searchQuery) return []
+      const { data } = await axios.get("/snippets/search", {
+        params: { q: searchQuery },
+      })
```
[the remark this answers is not in the document]
Comment (Ayushjhawar8) [reply src/components/PageSearchComponent.tsx:35]: i think this change will cause issue as this would double-append the base URL since it's already configured in the axios instance.

**Review by MustafaMulla29 — CHANGES_REQUESTED** [review]
https://github.com/user-attachments/assets/9abefa0f-cb4f-4763-bb43-23bdb2bbcbb1

The 'q' query has some issues, not updating properly

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
Note the search box background is not white on mobile, can be fixed on followup
